### ISSUE TITLE
delete doesn't work

### ISSUE THREAD

**Issue by ChillkroeteTTS** [matthiasn/meo#1]
When pressing the deletion button on an entry, nothing happens.

### output dev console
```
/Applications/iWasWhere.app/Contents/Resources/app/prod/renderer/renderer.js:274 :search-refresh-fn
/Applications/iWasWhere.app/Contents/Resources/app/prod/renderer/renderer.js:274 WARN: UNDEFINED SPEC :state/search
```

### Daily Log
```
{:timestamp 1510067339914, :deleted true}
```

**Comment by ChillkroeteTTS** [comment]
Although the footer tells me that Meo found entries, I can't see anyt
<img width="1202" alt="screen shot 2017-11-07 at 17 09 07" src="https://user-images.githubusercontent.com/15619240/32503797-733f7ac4-c3de-11e7-8b23-cc0d84377371.png">
.

**Comment by ChillkroeteTTS** [comment]
Update #3:
It seems like an empty search bar leads to the NullPointerException

**Comment by matthiasn** [comment]
Hey @ChillkroeteTTS, thanks for spotting and reporting this bug. I had seen this behavior before but only briefly and then it did not appear again for a long time. Can you please review the referenced commit. I think this would fix the symptoms of not having a number and then trying to use nil in some math operation. Probably warrants deeper inspection how those entries could exist in the first place, but no time to do that at the moment.

**Comment by ChillkroeteTTS** [comment]
Unfortunately I can't reproduce the bug anymore, with or without fix. It occurred very seldom after creating some more entries until it vanished completely after some time.
I'll close the issue for now and get in touch with you should I ever stumble on it again. Thanks for investigating!
