### ISSUE TITLE
Missing namespaces on build

### ISSUE THREAD

**Issue by simon-brooke** [matthiasn/meo#10]
I'm getting the following errors during build: 

on both MacOS and Ubuntu in both the terminal running `lein cljs-updater-dev` and also in the terminal running `lein cljs-renderer-dev`, on following the build instructions:

```
Caused by: clojure.lang.ExceptionInfo: No such namespace: react, could not locate react.cljs, react.cljc, or JavaScript source providing "react" in file out/updater/reagent/impl/component.cljs
```

on both MacOS and Ubuntu in the terminal running `lein cljs-main-dev` I'm getting:

```
Caused by: clojure.lang.ExceptionInfo: No such namespace: electron, could not locate electron.cljs, electron.cljc, or JavaScript source providing "electron" in file /home/simon/workspace/meo/src/cljs/meo/electron/main/runtime.cljs
```

Note also that the `README.md` has, at line 50,

```
    $ lein cljs-main-dev
    $ lein cljs-renderer-dev
    $ then cljs-updater-dev
```

I'm very nearly certain that should be `s/then/lein/`

**Comment by matthiasn** [comment]
Thanks, yes, corrected the README. About the namespaces though, sounds like the required `node_modules` cannot be found. Are you sure you ran the steps in the install script (either individually or via script) and also that `yarn install` finished successfully?

**Comment by simon-brooke** [comment]
H'mmm... yes, you're probably right, and it's probably due to extremely slow network connections. I restarted the `yarn install` step before lunch, just to check it had worked correctly, and it's still running now six hours later. I'll report back tomorrow whether or not it eventually worked!

**Comment by simon-brooke** [comment]
There's no proxy, but there's about 20 miles of very ancient copper. It's slow. I've got the satellite modem running this evening and I've got further. Probably something is wrong, but... 

I ran `yarn install`, and it completed successfully.

Following that I've now got `renderer.js` and `updater` to compile, by checking where they failed and running `npm install` on the missing namespaces. The following namespaces were missing:

```
npm install electron-log
npm install react
npm install react-dom
npm install electron
npm install globalize
npm install cldr-data
npm install iana-tz-data
npm install moment
npm install randomcolor
npm install emoji-flags
npm install leaflet
npm install react-responsive-carousel
npm install rome
npm install react-big-calendar
npm install electron-spellchecker
npm install draft-js
npm install draftjs-md-converter
npm install electron-updater
npm install crypto-js
npm install webdav
```

However `main.js` still won't compile; I'm getting the following:

```
Compiling ["prod/main/main.js"] failed.
clojure.lang.ExceptionInfo: failed compiling file:/Users/simon/workspace/meo/src/cljs/meo/electron/main/startup.cljs

...

Caused by: clojure.lang.ExceptionInfo: Unable to resolve var: lift-ns in this context at line 2843 file:/Users/simon/.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/cljs/pprint.cljs
```

It seems to me very improbable that there is really an error in `/cljs/pprint.cljs`; so there's probably something else still missing. I'll investigate further.

**Comment by matthiasn** [comment]
Hmm, I’ve seen this before, not too long ago. I think “lein clean” fixed it.

**Comment by simon-brooke** [comment]
OK, you're right. `lein clean` fixed problems on the Linux box, and the application started to the point that I have an open Electron window, with native menus 'Application', 'File', 'Edit', 'View', 'Capture'. The windo is entitled 'meo'. Unfortunately it currently has no content.

The terminal in which `npm run` was executed is showing large numbers of logging errors of the general form:

```
ERROR: Error: ENOENT: no such file or directory, open './data/webdav.edn' Exception in :electron/encryption when receiving message:[:sync/scan-images]

ERROR: Error: ENOENT: no such file or directory, open './data/webdav.edn' Exception in :electron/encryption when receiving message:[:sync/scan-inbox]

ERROR: Error: ENOENT: no such file or directory, open './data/webdav.edn' Exception in :electron/encryption when receiving message:[:sync/scan-images]

ERROR: Error: ENOENT: no such file or directory, open './data/webdav.edn' Exception in :electron/encryption when receiving message:[:sync/scan-inbox]

ERROR: Error: ENOENT: no such file or directory, open './data/webdav.edn' Exception in :electron/encryption when receiving message:[:sync/scan-images]

ERROR: Error: ENOENT: no such file or directory, open './data/webdav.edn' Exception in :electron/encryption when receiving message:[:sync/scan-inbox]
```
I'll see if I can dummy up a `webdav.edn` file, and see if that fixes anything!

**Comment by simon-brooke** [comment]
OK, I tried `cat /dev/null > webdav.edn`, and that worked to the extent that the error messages have changed:

```
15:29:01:158 INFO [meo.electron.main.encryption:116] - scan-images
ERROR: TypeError: Cannot read property '0' of null Exception in :electron/encryption when receiving message:[:sync/scan-images]

WARN: UNDEFINED SPEC :exec/js
15:29:11:158 INFO [meo.electron.main.encryption:80] - scan-inbox
ERROR: TypeError: Cannot read property '0' of null Exception in :electron/encryption when receiving message:[:sync/scan-inbox]

15:29:11:160 INFO [meo.electron.main.encryption:116] - scan-images
ERROR: TypeError: Cannot read property '0' of null Exception in :electron/encryption when receiving message:[:sync/scan-images]

WARN: UNDEFINED SPEC :exec/js
15:29:21:165 INFO [meo.electron.main.encryption:80] - scan-inbox
ERROR: TypeError: Cannot read property '0' of null Exception in :electron/encryption when receiving message:[:sync/scan-inbox]
```

I'm guessing I need to generate a valid `webdav.edn` file somehow...

**Comment by matthiasn** [comment]
Oh thanks, that's a great catch, you should not need this file unless you want to sync with the mobile app. Just fixed this by checking for the existence of the `webdav.edn` file first. If the file exists, it would still have to be valid though, and the format is likely to change very soon, so I would suggest deleting it for now. I will describe the whole sync mechanism in the next weeks, but that work isn't quite done yet and things will still change.
