### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [matthiasn/meo#14]
```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-7135/app/resources/app/node_modules/sharp/build/Release/sharp.node)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems.

Reference:
https://github.com/AppImage/appimage.github.io/pull/619

**Comment by matthiasn** [comment]
Hi, thanks for reporting this. Makes me start to wonder if it was a good idea to use [sharp](https://github.com/lovell/sharp) as it's also already cost me a few hours dealing with a wrong version of zlib.

Apparently, others are having the same issue:

https://github.com/RocketChat/Rocket.Chat/issues/9829

I might go back to [image-resizer](https://github.com/josephwilk/image-resizer) here, which should fix this issue. I will try to do so this afternoon/evening and report back to you.

**Comment by matthiasn** [comment]
@probonopd  I removed sharp, but I don't have a machine with Ubuntu 14.04 available for testing. Can you please try again? Thanks

**Comment by probonopd** [comment]
Thank you very much. This works.

**Comment by matthiasn** [comment]
Awesome, thanks for reporting. Let me know if anything else comes up, including questions about usage.
