### ISSUE TITLE
Missing icon on Linux

### ISSUE THREAD

**Issue by matthiasn** [matthiasn/meo#4]
On Mac, the proper logo shows up in the dock. On Ubuntu, that is not the case.

**Comment by simon-brooke** [comment]
Relates to the following electron issues:

* [electron-packager #125](https://github.com/electron-userland/electron-packager/pull/125)
* [electron-packager #128](https://github.com/electron-userland/electron-packager/issues/128)
* [electron-builder #2098](https://github.com/electron-userland/electron-builder/issues/2098)
* [electron #6205](https://github.com/electron/electron/issues/6205)

It seems from reading that the name `icon.png` may be magic, and that an image size of 128x128 seems to be preferred.

**Comment by simon-brooke** [comment]
The `--icon=` flag for the packager may also be relevant.

**Comment by matthiasn** [comment]
working fine recently when packaged as AppImage
